
import java.awt.Color;
import java.util.LinkedList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed
 */
public final class TheQuiz extends javax.swing.JFrame {

    private final LinkedList<Question> Quiz;
    private int Counter;
    private int Score;
    private boolean AnswerFlag;
    private Question Question;
    
    /**
     * Creates new form TheQuiz
     * @param Quiz
     */
    public TheQuiz(LinkedList Quiz) {
        this.Quiz=Quiz;
        this.Counter=0;
        this.Score=0;
        this.AnswerFlag = true;
        initComponents();
        initProblem();
    }
    
    private void initProblem(){
        // True False Problem
        TrueFalsePanel.setVisible(false);
        TrueRadio.setSelected(false);
        FalseRadio.setSelected(false);
        // Short Answer Problem
        ShortAnswerPanel.setVisible(false);
        ShortAnswerArea.setText(null);
        // Fill in Blank Problem
        FillinBlankPanel.setVisible(false);
        FillinBlankFeild.setText(null);
        // Multiple Choice Problem
        MultiplePanel.setVisible(false);
        MultipleBox.setSelectedItem(null);
        // Score Feild
        ScoreText.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NextQuestion = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        QuestionFeild = new javax.swing.JLabel();
        TrueFalsePanel = new javax.swing.JPanel();
        TrueRadio = new javax.swing.JRadioButton();
        FalseRadio = new javax.swing.JRadioButton();
        ShortAnswerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShortAnswerArea = new javax.swing.JTextArea();
        FillinBlankPanel = new javax.swing.JPanel();
        FillinBlankFeild = new javax.swing.JTextField();
        MultiplePanel = new javax.swing.JPanel();
        MultipleBox = new javax.swing.JComboBox();
        ScoreText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("The Quiz");
        setResizable(false);

        NextQuestion.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        NextQuestion.setText("Start");
        NextQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextQuestionActionPerformed(evt);
            }
        });

        QuestionFeild.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        QuestionFeild.setText("Press Start to start the Quiz");

        TrueRadio.setText("True");
        TrueRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrueRadioActionPerformed(evt);
            }
        });

        FalseRadio.setText("False");
        FalseRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalseRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TrueFalsePanelLayout = new javax.swing.GroupLayout(TrueFalsePanel);
        TrueFalsePanel.setLayout(TrueFalsePanelLayout);
        TrueFalsePanelLayout.setHorizontalGroup(
            TrueFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrueFalsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TrueRadio)
                .addGap(18, 18, 18)
                .addComponent(FalseRadio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TrueFalsePanelLayout.setVerticalGroup(
            TrueFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrueFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(TrueRadio)
                .addComponent(FalseRadio))
        );

        ShortAnswerArea.setColumns(20);
        ShortAnswerArea.setRows(5);
        jScrollPane1.setViewportView(ShortAnswerArea);

        javax.swing.GroupLayout ShortAnswerPanelLayout = new javax.swing.GroupLayout(ShortAnswerPanel);
        ShortAnswerPanel.setLayout(ShortAnswerPanelLayout);
        ShortAnswerPanelLayout.setHorizontalGroup(
            ShortAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ShortAnswerPanelLayout.setVerticalGroup(
            ShortAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShortAnswerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout FillinBlankPanelLayout = new javax.swing.GroupLayout(FillinBlankPanel);
        FillinBlankPanel.setLayout(FillinBlankPanelLayout);
        FillinBlankPanelLayout.setHorizontalGroup(
            FillinBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FillinBlankFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        FillinBlankPanelLayout.setVerticalGroup(
            FillinBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FillinBlankPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FillinBlankFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MultiplePanelLayout = new javax.swing.GroupLayout(MultiplePanel);
        MultiplePanel.setLayout(MultiplePanelLayout);
        MultiplePanelLayout.setHorizontalGroup(
            MultiplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MultipleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MultiplePanelLayout.setVerticalGroup(
            MultiplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MultiplePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MultipleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ScoreText.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        ScoreText.setText("Press Start to start the Quiz");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TrueFalsePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuestionFeild)
                    .addComponent(ShortAnswerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FillinBlankPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultiplePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuestionFeild)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrueFalsePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShortAnswerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FillinBlankPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MultiplePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScoreText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(NextQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NextQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TrueRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrueRadioActionPerformed
        FalseRadio.setSelected(false);
    }//GEN-LAST:event_TrueRadioActionPerformed

    private void FalseRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalseRadioActionPerformed
        TrueRadio.setSelected(false);
    }//GEN-LAST:event_FalseRadioActionPerformed

    private void NextQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextQuestionActionPerformed
        NextQuestion.setText("Next..");
        AnswerFlag = !AnswerFlag;
        if(AnswerFlag)checkAnswer();
        initProblem();
        if(Counter != Quiz.size())getQuestion();
        else FinishUp();
    }//GEN-LAST:event_NextQuestionActionPerformed

    private void FinishUp(){
        NextQuestion.setText("Finished");
        NextQuestion.setEnabled(false);
        ScoreText.setVisible(true);
        double Mark = ((double)this.Score)/((double)this.Counter);
        QuestionFeild.setText("You Answered "+Score+" Correct Answers out of "+Counter);
        if(Mark < 0.8){
            ScoreText.setText("Failed");
            ScoreText.setForeground(Color.red);
        }else{
            ScoreText.setText("Passed");
            ScoreText.setForeground(Color.green);
        }
    }
    
    private void checkAnswer(){
        boolean checkAnswer = false;
        if(Question instanceof TrueFalseQuestion){
            checkAnswer = Question.checkAnswer(TrueRadio.isSelected());
        }else if(Question instanceof ShortAnswerQuestion){
            System.out.println(ShortAnswerArea.getText());
            checkAnswer = Question.checkAnswer(ShortAnswerArea.getText());
        }else if(Question instanceof FillInBlankQuestion){
            checkAnswer = Question.checkAnswer(FillinBlankFeild.getText());
        }else if(Question instanceof MultipleChoiceQuestion){
            checkAnswer = Question.checkAnswer(MultipleBox.getSelectedItem().toString());
        }
        if(checkAnswer)Score++;
    }
    
    private void getQuestion(){
        this.Question = this.Quiz.get(Counter);
        ++Counter;
        QuestionFeild.setText(Question.getQuestion());
        if(Question instanceof TrueFalseQuestion){
            TrueFalsePanel.setVisible(true);
        }else if(Question instanceof ShortAnswerQuestion){
            ShortAnswerPanel.setVisible(true);
        }else if(Question instanceof FillInBlankQuestion){
            FillinBlankPanel.setVisible(true);
        }else if(Question instanceof MultipleChoiceQuestion){
            MultiplePanel.setVisible(true);
        }    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FalseRadio;
    private javax.swing.JTextField FillinBlankFeild;
    private javax.swing.JPanel FillinBlankPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JComboBox MultipleBox;
    private javax.swing.JPanel MultiplePanel;
    private javax.swing.JButton NextQuestion;
    private javax.swing.JLabel QuestionFeild;
    private javax.swing.JLabel ScoreText;
    private javax.swing.JTextArea ShortAnswerArea;
    private javax.swing.JPanel ShortAnswerPanel;
    private javax.swing.JPanel TrueFalsePanel;
    private javax.swing.JRadioButton TrueRadio;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
